### ISSUE TITLE
👑 [需求] 支持 manifest v3 版

### ISSUE THREAD

**Issue by arvinxx** [arvinxx/umi-plugin-extensions#625]
### 🥰 需求描述

需要支持 v3 的配置

<img width="721" alt="image" src="https://user-images.githubusercontent.com/28616219/184522132-1c161bf6-c9ad-40d6-b5de-1de39797a603.png">

https://developer.chrome.com/docs/extensions/mv3/intro/

### 🧐 解决方案

和 umi4 的迁移方案一起考虑，正式发布 1.0 -> umi4 + manifest 3

### 🚑 其他信息

迁移说明：https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by lijiawei0602** [comment]
请问V3版本支持有预计时间吗？或者有没有快死解决的方案来使用umi-chrome-extensions-template脚手架完成V3

**Comment by WihteCrow** [comment]
+1

**Comment by arvinxx** [comment]
已发布

**Comment by tonywu6** [comment]
https://github.com/arvinxx/umi-plugin-extensions/search?q=server_worker

@arvinxx 这里面 `server_worker` 是不是都应该是 `service_worker`
